image: Visual Studio 2019

platform:
    - 64
    
configuration:
    - Debug

install:
    - ps: Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
    
# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - appveyor

build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
    - xmake build -yv tests
    - xmake run tests
